calculate_price:
    path: /calculate-price
    controller: App\Controller\PriceController::calculatePrice
    methods: POST

purchase:
    path: /purchase
    controller: App\Controller\PurchaseController::purchase
    methods: POST